version: '3'

services:
  tasks:
    image: quarkus-form/quartz:latest
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres/quarkus-form
    networks:
      - tasks-network
    depends_on:
      - postgres

  nginx:
    image: nginx:1.17.6
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tasks
    ports:
      - 9099:9099
    networks:
      - tasks-network

  postgres:
    image: postgres:13.3
    container_name: quarkus-form
    environment:
      - POSTGRES_USER=quarkus-form
      - POSTGRES_PASSWORD=quarkus-form
      - POSTGRES_DB=quarkus-form
    ports:
      - 5432:5432
    networks:
      - tasks-network

  frontend:
    build: src/main/resources/META-INF/view
    ports:
      - "3000:80"
    networks:
      - tasks-network

networks:
  tasks-network:
    driver: bridge